### ISSUE TITLE
License identifiers break all builds

### ISSUE THREAD

**Issue by jess-sch** [flathub/org.bluej.BlueJ#2]
SPDX updated the spec and deprecated the old license names, so they're not accepted anymore by appdata validation.
If anyone knows how to use the WITH operator in appdata, please tell me.

**Comment by TingPing** [comment]
Hmm, it looked like your usage was correct: `GPL-2.0-only WITH Classpath-exception-2.0`.

CC @hughsie

**Comment by hughsie** [comment]
It's `GPL-2.0-with-classpath-exception` -- we can't break API to support the new names without updating soname and getting ~800 upstream projects to change the deprecated syntax. It was a dumb move for the SPDX to change the format like they did.

**Comment by jess-sch** [comment]
> It's `GPL-2.0-with-classpath-exception`

It isn't though. I [was initially using this](https://github.com/flathub/org.bluej.BlueJ/commit/e4c7d95c6640d1a591e70cb05ee356611951ad9b) but I changed it because the appdata validation failed the [build process](https://flathub.org/builds/#/builders/2/builds/289/steps/12/logs/stdio).

```
builddir/files/share/appdata/org.bluej.BlueJ.appdata.xml: FAILED:
• tag-invalid           : <metadata_license> is not valid [GPL-2.0-with-classpath-exception]
Validation of files failed
program finished with exit code 1
```

I suspect someone updated the list of valid license IDs without considering that exceptions require special syntax - or it checks the existence with an HTTP request, failing when it 404s or gets a deprecation notice.

**Comment by hughsie** [comment]
Right, `GPL-2.0-with-classpath-exception` is a valid project licence. It's not a valid metadata license. The metadata licence has to be an acceptable content licence, not a licence designed for code. There's a listed subset in the docs of acceptable content licences.

**Comment by jess-sch** [comment]
... but the metadata has explicitly been released under the GPL by upstream. What should I do in this case?
Back when I first submitted the flatpak, this was accepted.

**Comment by hughsie** [comment]
> What should I do in this case

Ask them to use one of the approved metadata licenses: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license
