### ISSUE TITLE
GNOME 40 runtime is EOL

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.bluej.BlueJ#6]
The package should be updated to use GNOME 42 (or Freedesktop 21.08 if GNOME is not necessary)

**Comment by mikebarkmin** [comment]
Since Greenfoot and BlueJ using the same base, using parts of the Greenfoot config, which uses Freedesktop, should work. https://github.com/flathub/org.greenfoot.Greenfoot/blob/master/org.greenfoot.Greenfoot.json

**Comment by Zorono** [comment]
> The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.


@jess-sch

**Comment by hfiguiere** [comment]
Was fixed but the issue never closed

  "runtime-version" : "44",
